name: misskey
description: This library provides the easiest and powerful Dart/Flutter library for Misskey API.
version: 0.0.1
repository: https://github.com/myConsciousness/misskey
issue_tracker: https://github.com/myConsciousness/misskey/issues

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  http: ^0.13.6
  universal_io: ^2.2.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.24.2
  build_runner: ^2.3.3
  json_serializable: ^6.6.2
  freezed: ^2.3.3
  import_sorter: ^4.6.0
  mockito: ^5.4.0

import_sorter:
  emojis: true